// Code generated by scripts/gen-contract (make contract). DO NOT EDIT.
// Fonte de verdade: os structs Go em internal/ipc e nos pacotes de domínio
// referenciados (policy, preset, pomodoro, analytics, schedule, tamper).
// Edite o Go e rode `make contract` — nunca edite este arquivo à mão.
// Regra do AGENT.md: mudou o contrato IPC, atualize CLI + tray + web + este
// arquivo no mesmo commit (regenerado).

export interface Block {
  domain: string;
  started_at: string; // RFC3339
  expires_at: string; // RFC3339
  resolved_ips: string[];
  allowlist?: string[]; // Allowlist names the domains still reachable under the all-internet
}

export interface Preset {
  name: string;
  label: string;
  domains: string[];
}

export interface PomodoroState {
  active: boolean;
  preset?: string;
  phase?: "work" | "rest";
  cycle?: number;
  cycles?: number;
  started_at?: string; // RFC3339
  phase_until?: string; // RFC3339
}

export interface DayStat {
  day: string;
  duration: number; // nanosegundos
  sessions: number;
}

export interface DomainStat {
  domain: string;
  duration: number; // nanosegundos
}

export interface Stats {
  total_sessions: number;
  total_focus: number; // nanosegundos
  per_day: DayStat[];
  per_domain: DomainStat[];
  streak: number; // Streak is the current run of consecutive days with focus.
}

export interface LabelStat {
  label: string;
  duration: number; // nanosegundos
  sessions: number;
}

export interface FocusSession {
  start: string; // RFC3339
  end: string; // RFC3339
  preset: string;
  label?: string;
  domains: string[];
  work_min: number;
  rest_min: number;
  cycles: number;
  focus: number; // nanosegundos
  strict: boolean;
}

export interface ScheduleRule {
  id: string;
  label?: string;
  preset: string;
  days: number[]; // 0 = domingo
  start: string;
  end: string;
  windows?: string[]; // Windows lists optional "HH:MM-HH:MM" time windows (multiple per rule,
  enabled: boolean;
}

export interface TamperEvent {
  at: string; // RFC3339
  source: string;
  action: string;
  detail?: string;
}

export interface ApiRequest {
  action: string;
  domain?: string;
  duration?: string;
  preset?: string;
  work_min?: number;
  rest_min?: number;
  cycles?: number;
  strict?: boolean;
  save?: boolean; // Save persists the resolved work/rest/cycles as the defaults for the
  label?: string; // Label names the pomodoro session (a "mission", ex: --label "Estudar ENEM")
  mission?: string;
  channel?: string; // Channel selects the release channel for the update action: "" or
  preset_name?: string; // PresetName/Label/Domains describe a custom preset for preset-add/remove.
  preset_label?: string;
  preset_domains?: string[];
  schedule_rule?: ScheduleRule; // ScheduleRule/ScheduleID drive the schedule-add/remove actions.
  schedule_id?: string;
  ics_content?: string; // ICSContent/ICSPreset drive schedule-import (raw .ics file content).
  ics_preset?: string;
  allowlist?: string[]; // Allowlist lists the domains still reachable under the block-all action
  goal_minutes?: number; // GoalMinutes drives the goal-set action (daily focus goal in minutes).
  app_name?: string; // AppName drives the apps-add/apps-remove actions (process denylist).
  name?: string; // Name is the focus-session/mission label for the pomodoro action.
  user_name?: string; // UserName/UserPassword drive the user-* actions (web login and user
  user_password?: string;
  upstream?: string; // Upstream drives the dns-set-upstream action: the resolver (host[:port])
  extend?: boolean; // Extend/Replace resolve the conflict of the user-driven block action:
  replace?: boolean;
}

export interface ApiResponse {
  success: boolean;
  message?: string;
  blocks?: Block[];
  expected_doh?: boolean;
  doh_active?: boolean;
  firewall_rules?: number;
  protection_error?: string;
  update_available?: boolean;
  update_version?: string;
  current_version?: string;
  presets?: Preset[];
  pomodoro?: PomodoroState;
  stats?: Stats;
  schedules?: ScheduleRule[];
  goal?: number; // Goal is the current daily focus goal (goal-get / status).
  pomodoro_work?: number; // PomodoroWork/Rest/Cycles are the resolved defaults (pomodoro-defaults).
  pomodoro_rest?: number;
  pomodoro_cycles?: number;
  label_stats?: LabelStat[]; // LabelStats aggregates focus per named mission (mission command).
  sessions?: FocusSession[]; // Sessions lists the most recent completed focus sessions (sessions
  apps?: string[]; // Apps is the process denylist (apps-list).
  tamper_log?: TamperEvent[]; // TamperLog lists detected tamper attempts (tamper-log).
  conflict?: boolean; // Conflict marks a failed "block" request that hit an already-active block
  conflict_block?: Block; // ConflictBlock carries the existing block that caused the conflict, so the
  users?: string[]; // Users lists the web UI usernames (user-list) — names only, never hashes.
  user_is_admin?: boolean; // UserIsAdmin reports whether the user-verify credentials belong to the
  update_pending_reboot?: boolean; // UpdatePendingReboot marks an update that could not replace the running
  dns_enabled?: boolean; // DNSEnabled reports whether the DNS sinkhole server should be running
  dns_listening?: boolean;
  dns_addr?: string;
  dns_upstream?: string;
  dns_queries?: number;
  dns_blocked?: number;
  dns_bind_error?: string;
}

