// Code generated by scripts/gen-contract (make contract). DO NOT EDIT.
// Fonte de verdade: os structs Go em internal/transport/ipc e nos pacotes de domínio
// referenciados (policy, preset, pomodoro, analytics, schedule, tamper,
// metrics).
// Edite o Go e rode `make contract` — nunca edite este arquivo à mão.
// Regra do AGENT.md: mudou o contrato IPC, atualize CLI + tray + web + este
// arquivo no mesmo commit (regenerado).

export interface Block {
  domain: string;
  started_at: string; // RFC3339
  expires_at: string; // RFC3339
  resolved_ips: string[];
  allowlist?: string[]; // Allowlist names the domains still reachable under the all-internet
  source?: "user" | "clock-guard"; // Source tags the block's owner (user panic vs. the clock guard's
}

// Preset is a named group of domains blocked together by category.
export interface Preset {
  name: string;
  label: string;
  domains: string[];
}

// State is the observable session snapshot (also sent over IPC).
export interface PomodoroState {
  active: boolean;
  preset?: string;
  phase?: "work" | "rest";
  cycle?: number;
  cycles?: number;
  started_at?: string; // RFC3339
  phase_until?: string; // RFC3339
}

// DayStat aggregates focus for a single calendar day.
export interface DayStat {
  day: string;
  duration: number; // nanosegundos
  sessions: number;
}

// DomainStat aggregates focus attributed to a single blocked domain (each
export interface DomainStat {
  domain: string;
  duration: number; // nanosegundos
}

// Stats is the aggregated report returned by the "stats" IPC action.
export interface Stats {
  total_sessions: number;
  total_focus: number; // nanosegundos
  per_day: DayStat[];
  per_domain: DomainStat[];
  streak: number; // Streak is the current run of consecutive days with focus.
}

// LabelStat aggregates focus for one named mission (sessions with a Label).
export interface LabelStat {
  label: string;
  duration: number; // nanosegundos
  sessions: number;
}

// Session is one completed focus session, recorded by the pomodoro controller
export interface FocusSession {
  start: string; // RFC3339
  end: string; // RFC3339
  preset: string;
  label?: string;
  domains: string[];
  work_min: number;
  rest_min: number;
  cycles: number;
  focus: number; // nanosegundos
  strict: boolean;
}

// Rule is a recurring block window. Days are time.Weekday (0=Sunday).
export interface ScheduleRule {
  id: string;
  label?: string;
  preset: string;
  days: number[]; // 0 = domingo
  start: string;
  end: string;
  windows?: string[]; // Windows lists optional "HH:MM-HH:MM" time windows (multiple per rule,
  enabled: boolean;
}

// Device is one network device with an optional policy override.
export interface Device {
  ip: string;
  mac?: string;
  name?: string;
  policy?: "inherit" | "block_all" | "allow_list"; // Policy "" e "inherit" são equivalentes (regra global decide).
  allowed_domains?: string[]; // AllowedDomains are the only domains reachable under PolicyAllowList
}

// Achievement is one badge. Unlocked is derived from the stats; Progress is
export interface Achievement {
  id: string;
  name: string;
  description: string;
  icon?: string;
  unlocked: boolean;
  progress: number;
}

// Config é o agendamento do relatório semanal, persistido em reports.json.
export interface ReportConfig {
  enabled: boolean;
  day_of_week?: number;
  hour?: number;
  minute?: number;
  export_path?: string;
}

// BlockedQuery is one sinkholed DNS request, recorded by the dnsserver hook.
export interface TelemetryEntry {
  domain: string;
  client_ip: string;
  timestamp: string; // RFC3339
}

// Summary aggregates blocked queries per domain: count, last client IPs (up
export interface TelemetrySummary {
  domain: string;
  count: number;
  last_ips: string[];
  last_blocked?: string; // RFC3339
}

// Event is one detected tamper attempt.
export interface TamperEvent {
  at: string; // RFC3339
  source: "hosts" | "state" | "clock"; // Source is where the tamper was detected: the hosts file ("hosts"), the
  action: "restore" | "reconcile" | "lockdown"; // Action is what was done: "restore" (external edit reverted), "reconcile"
  detail?: string;
}

// ActionStat is the latency aggregate of one action (IPC or HTTP proxy).
export interface ActionStat {
  action: string;
  count: number;
  total: number; // nanosegundos
  avg: number; // nanosegundos
  max: number; // nanosegundos
  p50: number; // nanosegundos
  p95: number; // nanosegundos
  p99: number; // nanosegundos
  last: number; // nanosegundos
}

export interface ApiRequest {
  action: string;
  domain?: string;
  duration?: string;
  preset?: string;
  work_min?: number;
  rest_min?: number;
  cycles?: number;
  strict?: boolean;
  save?: boolean; // Save persists the resolved work/rest/cycles as the defaults for the
  label?: string; // Label names the pomodoro session (a "mission", ex: --label "Estudar ENEM")
  mission?: string;
  channel?: string; // Channel selects the release channel for the update action: "" or
  preset_name?: string; // PresetName/Label/Domains describe a custom preset for preset-add/remove.
  preset_label?: string;
  preset_domains?: string[];
  schedule_rule?: ScheduleRule; // ScheduleRule/ScheduleID drive the schedule-add/remove actions.
  schedule_id?: string;
  ics_content?: string; // ICSContent/ICSPreset drive schedule-import (raw .ics file content).
  ics_preset?: string;
  allowlist?: string[]; // Allowlist lists the domains still reachable under the block-all action
  goal_minutes?: number; // GoalMinutes drives the goal-set action (daily focus goal in minutes).
  app_name?: string; // AppName drives the apps-add/apps-remove actions (process denylist).
  name?: string; // Name is the focus-session/mission label for the pomodoro action.
  user_name?: string; // UserName/UserPassword drive the user-* actions (web login and user
  user_password?: string;
  upstream?: string; // Upstream drives the dns-set-upstream action: the resolver (host[:port])
  extend?: boolean; // Extend/Replace resolve the conflict of the user-driven block action:
  replace?: boolean;
  since?: number; // Since drives the event-subscribe long-poll (Fase 7): the last event
  reset?: boolean; // Reset clears the daemon's latency metrics before snapshotting (Fase 8 —
  telemetry_limit?: number; // TelemetryLimit bounds the dns-telemetry entries (0 = daemon default 50).
  interceptor_enabled?: boolean; // InterceptorEnabled drives the interceptor-set action (Fase 3): whether
  device?: Device; // Device drives the devices-upsert action (Fase 4 — edição Server): the
  device_ip?: string; // DeviceIP drives devices-remove: the IP of the device whose rule is
  report_config?: ReportConfig; // ReportConfig drives reports-config-set (Fase 5.1): the weekly report
  report_export_path?: string; // ReportExportPath drives reports-generate: an optional path override
}

export interface ApiResponse {
  success: boolean;
  message?: string;
  code?: string; // Code is a stable, machine-readable error identifier (aditivo — Fase 2 do
  blocks?: Block[];
  expected_doh?: boolean;
  doh_active?: boolean;
  firewall_rules?: number;
  protection_error?: string;
  update_available?: boolean;
  update_version?: string;
  current_version?: string;
  presets?: Preset[];
  pomodoro?: PomodoroState;
  stats?: Stats;
  schedules?: ScheduleRule[];
  goal?: number; // Goal is the current daily focus goal (goal-get / status).
  pomodoro_work?: number; // PomodoroWork/Rest/Cycles are the resolved defaults (pomodoro-defaults).
  pomodoro_rest?: number;
  pomodoro_cycles?: number;
  label_stats?: LabelStat[]; // LabelStats aggregates focus per named mission (mission command).
  sessions?: FocusSession[]; // Sessions lists the most recent completed focus sessions (sessions
  apps?: string[]; // Apps is the process denylist (apps-list).
  tamper_log?: TamperEvent[]; // TamperLog lists detected tamper attempts (tamper-log).
  conflict?: boolean; // Conflict marks a failed "block" request that hit an already-active block
  conflict_block?: Block; // ConflictBlock carries the existing block that caused the conflict, so the
  rev?: number; // Rev/Events come from the event-subscribe long-poll (Fase 7): Rev is the
  events?: Event[];
  metrics?: ActionStat[]; // Metrics is the daemon's latency snapshot per action (metrics action,
  users?: string[]; // Users lists the web UI usernames (user-list) — names only, never hashes.
  user_is_admin?: boolean; // UserIsAdmin reports whether the user-verify credentials belong to the
  update_pending_reboot?: boolean; // UpdatePendingReboot marks an update that could not replace the running
  dns_enabled?: boolean; // DNSEnabled reports whether the DNS sinkhole server should be running
  dns_listening?: boolean;
  dns_addr?: string;
  dns_upstream?: string;
  dns_queries?: number;
  dns_blocked?: number;
  dns_bind_error?: string;
  lan_ip?: string; // LanIP/LanMAC report the machine's own IPv4 and MAC on the LAN
  lan_mac?: string;
  telemetry_entries?: TelemetryEntry[]; // Telemetry reports the DNS sinkhole's blocked-query activity
  telemetry_summary?: TelemetrySummary[];
  telemetry_total?: number;
  telemetry_limit?: number; // TelemetryLimit echoes the requested limit so the UI can paginate (0 =
  interceptor_enabled?: boolean; // InterceptorEnabled reports the persisted Focus Interceptor Page flag
  devices?: Device[]; // Devices lists the per-device policies (devices-list, Fase 4 — edição
  report_config?: ReportConfig; // Fase 5.1) and ReportPath the generated files (reports-generate).
  report_path?: string;
  achievements?: Achievement[]; // Achievements lists the gamification badges with unlock/progress derived
}

// Event is one daemon state-change notification (event-subscribe). Events are
export interface Event {
  type: string;
  at: string; // RFC3339
}

