// Package analytics records completed focus sessions and renders focus
// statistics (ASCII bar charts) for the "focusguard stats" command. Sessions
// are appended to a JSONL file (one JSON object per line) and aggregated on
// demand — the file is the source of truth for analytics (unlike state.json,
// which is a RAM mirror). Corrupt or partial lines are skipped on read, so a
// torn write never aborts the report.
package analytics

import (
	"bufio"
	"encoding/json"
	"fmt"
	"html"
	"os"
	"sort"
	"strings"
	"sync"
	"time"
)

// Session is one completed focus session, recorded by the pomodoro controller
// at the end (natural completion or stop). Label is the optional session name
// (a "mission", e.g. "Estudar ENEM") used by focusguard mission/report.
// Mirrored in the web UI as FocusSession (generated by make contract).
type Session struct {
	Start   time.Time     `json:"start"`
	End     time.Time     `json:"end"`
	Preset  string        `json:"preset"`
	Label   string        `json:"label,omitempty"`
	Domains []string      `json:"domains"`
	WorkMin int           `json:"work_min"`
	RestMin int           `json:"rest_min"`
	Cycles  int           `json:"cycles"`
	Focus   time.Duration `json:"focus"`
	Strict  bool          `json:"strict"`
}

// DayStat aggregates focus for a single calendar day.
type DayStat struct {
	Day      string        `json:"day"`
	Duration time.Duration `json:"duration"`
	Sessions int           `json:"sessions"`
}

// DomainStat aggregates focus attributed to a single blocked domain (each
// session's focus is attributed to every domain it blocked).
type DomainStat struct {
	Domain   string        `json:"domain"`
	Duration time.Duration `json:"duration"`
}

// LabelStat aggregates focus for one named mission (sessions with a Label).
type LabelStat struct {
	Label    string        `json:"label"`
	Duration time.Duration `json:"duration"`
	Sessions int           `json:"sessions"`
}

// Stats is the aggregated report returned by the "stats" IPC action.
type Stats struct {
	TotalSessions int           `json:"total_sessions"`
	TotalFocus    time.Duration `json:"total_focus"`
	PerDay        []DayStat     `json:"per_day"`
	PerDomain     []DomainStat  `json:"per_domain"`
	// Streak is the current run of consecutive days with focus.
	Streak int `json:"streak"`
}

// Recorder appends sessions to a JSONL file. An empty path keeps the recorder
// in memory (tests and daemon fallback).
type Recorder struct {
	mu     sync.Mutex
	path   string
	memory []Session

	// cache incremental do arquivo JSONL: espelha o que este processo já leu
	// ou gravou. fileEOF/fileMtime formam o fingerprint do arquivo no último
	// estado conhecido — quando um Sessions() o encontra intacto, devolve o
	// cache sem reler o disco (um `stats` repetido deixa de recomputar o
	// arquivo inteiro). Qualquer divergência (append externo, reescrita,
	// truncamento) força uma releitura integral: o arquivo continua sendo a
	// fonte da verdade.
	cache     []Session
	loaded    bool
	fileEOF   int64
	fileMtime time.Time
}

// NewRecorder returns a Recorder writing to path, or an in-memory recorder
// when path is empty.
func NewRecorder(path string) *Recorder {
	return &Recorder{path: path}
}

// Record appends one session to the file (or memory).
func (r *Recorder) Record(s Session) {
	r.mu.Lock()
	defer r.mu.Unlock()

	if r.path == "" {
		r.memory = append(r.memory, s)
		return
	}

	data, err := json.Marshal(s)
	if err != nil {
		return
	}

	// Se o arquivo estiver exatamente no estado que conhecemos antes da
	// escrita, o append próprio estende o cache de forma limpa; caso contrário
	// (mudança externa no meio), o cache já está obsoleto e o próximo
	// Sessions() relê tudo — um append de outro processo não pode ser perdido.
	clean := false
	if fi, err := os.Stat(r.path); err == nil {
		clean = r.loaded && fi.Size() == r.fileEOF && fi.ModTime().Equal(r.fileMtime)
	} else if os.IsNotExist(err) {
		clean = true // arquivo recém-criado: nada para divergir
	}

	f, err := os.OpenFile(r.path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0600)
	if err != nil {
		return
	}
	defer f.Close()
	if _, err := f.Write(append(data, '\n')); err != nil {
		return
	}

	if fi, err := os.Stat(r.path); err == nil {
		r.fileEOF = fi.Size()
		r.fileMtime = fi.ModTime()
		if clean {
			r.cache = append(r.cache, s)
			r.loaded = true
		} else {
			r.cache = nil
			r.loaded = false
		}
	}
}

// Sessions returns every session read from the file (or memory), skipping
// corrupt lines. A missing file yields an empty list without error. Repeats
// over an unchanged file hit the incremental cache instead of re-reading and
// re-parsing the whole JSONL.
func (r *Recorder) Sessions() ([]Session, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	if r.path == "" {
		return append([]Session(nil), r.memory...), nil
	}

	fi, err := os.Stat(r.path)
	if os.IsNotExist(err) {
		r.cache = nil
		r.loaded = false
		return nil, nil
	}
	if err != nil {
		return nil, err
	}

	if r.loaded && fi.Size() == r.fileEOF && fi.ModTime().Equal(r.fileMtime) {
		return append([]Session(nil), r.cache...), nil
	}

	f, err := os.Open(r.path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var sessions []Session
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" {
			continue
		}
		var s Session
		if err := json.Unmarshal([]byte(line), &s); err != nil {
			continue // linha corrompida/parcial — nunca aborta a leitura
		}
		sessions = append(sessions, s)
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}

	r.cache = sessions
	r.loaded = true
	r.fileEOF = fi.Size()
	r.fileMtime = fi.ModTime()
	return append([]Session(nil), r.cache...), nil
}

// RecentSessions returns up to `limit` sessions ordered by End descending
// (newest first). A non-positive limit yields an empty slice. The input slice
// is not mutated.
func RecentSessions(sessions []Session, limit int) []Session {
	if limit <= 0 {
		return []Session{}
	}
	sorted := append([]Session(nil), sessions...)
	sort.SliceStable(sorted, func(i, j int) bool {
		return sorted[i].End.After(sorted[j].End)
	})
	if len(sorted) > limit {
		sorted = sorted[:limit]
	}
	return sorted
}

// Summarize aggregates sessions into a Stats report: totals, a per-day window
// of the last `days` days (zero-filled, oldest first) and per-domain focus
// sorted by duration descending.
func Summarize(sessions []Session, days int, now time.Time) *Stats {
	st := &Stats{
		PerDay:    make([]DayStat, 0, days),
		PerDomain: []DomainStat{},
	}

	dayTotals := make(map[string]time.Duration)
	dayCounts := make(map[string]int)
	domainTotals := make(map[string]time.Duration)

	for _, s := range sessions {
		st.TotalSessions++
		st.TotalFocus += s.Focus

		day := s.Start.Format("2006-01-02")
		dayTotals[day] += s.Focus
		dayCounts[day]++

		for _, d := range s.Domains {
			domainTotals[d] += s.Focus
		}
	}

	for i := days - 1; i >= 0; i-- {
		day := now.AddDate(0, 0, -i).Format("2006-01-02")
		st.PerDay = append(st.PerDay, DayStat{
			Day:      day,
			Duration: dayTotals[day],
			Sessions: dayCounts[day],
		})
	}

	for d, dur := range domainTotals {
		st.PerDomain = append(st.PerDomain, DomainStat{Domain: d, Duration: dur})
	}
	sort.Slice(st.PerDomain, func(i, j int) bool {
		if st.PerDomain[i].Duration != st.PerDomain[j].Duration {
			return st.PerDomain[i].Duration > st.PerDomain[j].Duration
		}
		return st.PerDomain[i].Domain < st.PerDomain[j].Domain
	})

	st.Streak = ComputeStreak(sessions, now)
	return st
}

// SummarizeByLabel aggregates only the sessions whose Label matches want,
// producing a Stats report scoped to that mission (used by the "stats
// --mission <nome>" filter).
func SummarizeByLabel(sessions []Session, want string, days int, now time.Time) *Stats {
	var scoped []Session
	for _, s := range sessions {
		if s.Label == want {
			scoped = append(scoped, s)
		}
	}
	return Summarize(scoped, days, now)
}

// SummarizeLabels aggregates the total focus and session count per named
// mission (sessions with a Label), sorted by duration descending. Sessions
// without a label are excluded.
func SummarizeLabels(sessions []Session) []LabelStat {
	totals := make(map[string]*LabelStat)
	for _, s := range sessions {
		if s.Label == "" {
			continue
		}
		ls, ok := totals[s.Label]
		if !ok {
			ls = &LabelStat{Label: s.Label}
			totals[s.Label] = ls
		}
		ls.Duration += s.Focus
		ls.Sessions++
	}
	out := make([]LabelStat, 0, len(totals))
	for _, ls := range totals {
		out = append(out, *ls)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Duration != out[j].Duration {
			return out[i].Duration > out[j].Duration
		}
		return out[i].Label < out[j].Label
	})
	return out
}

// ComputeStreak returns the number of consecutive days (ending today, or
// yesterday if today has no focus yet — a fresh day must not kill the streak
// before the user starts) with at least one recorded session.
func ComputeStreak(sessions []Session, now time.Time) int {
	focused := make(map[string]bool)
	for _, s := range sessions {
		focused[s.Start.Format("2006-01-02")] = true
	}

	streak := 0
	cursor := now
	if !focused[now.Format("2006-01-02")] {
		cursor = cursor.AddDate(0, 0, -1) // hoje ainda não conta — começa de ontem
	}
	for focused[cursor.Format("2006-01-02")] {
		streak++
		cursor = cursor.AddDate(0, 0, -1)
	}
	return streak
}

// ExportCSV renders the per-day window as comma-separated values with a
// header row, minutes as integers (machine-readable, spreadsheet-friendly).
func ExportCSV(st *Stats) string {
	var b strings.Builder
	b.WriteString("day,focus_minutes,sessions\n")
	for _, d := range st.PerDay {
		fmt.Fprintf(&b, "%s,%d,%d\n", d.Day, int(d.Duration/time.Minute), d.Sessions)
	}
	return b.String()
}

// ExportJSON marshals the whole report as indented JSON.
func ExportJSON(st *Stats) (string, error) {
	data, err := json.MarshalIndent(st, "", "  ")
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// ExportHTML renders the report as a self-contained HTML page (inline CSS, no
// external assets) suitable for saving to a file and opening in a browser:
// summary cards, per-day bar chart and per-domain ranking. All dynamic text
// is HTML-escaped.
func ExportHTML(st *Stats) string {
	var b strings.Builder
	b.WriteString("<!DOCTYPE html>\n<html lang=\"pt-BR\">\n<head>\n<meta charset=\"utf-8\">\n")
	b.WriteString("<title>FocusGuard — Estatísticas de foco</title>\n")
	b.WriteString(`<style>
    :root { color-scheme: light dark; }
    body { font-family: system-ui, -apple-system, sans-serif; max-width: 760px; margin: 2rem auto; padding: 0 1rem; }
    h1 { margin-bottom: .25rem; }
    .sub { color: #888; margin-bottom: 1.5rem; }
    .cards { display: flex; gap: 1rem; flex-wrap: wrap; margin-bottom: 2rem; }
    .card { flex: 1; min-width: 140px; border: 1px solid #ddd; border-radius: 10px; padding: .75rem 1rem; }
    .card .k { font-size: .8rem; color: #888; text-transform: uppercase; letter-spacing: .04em; }
    .card .v { font-size: 1.4rem; font-weight: 700; margin-top: .2rem; }
    h2 { font-size: 1.05rem; margin: 1.75rem 0 .75rem; }
    .bar-row { display: flex; align-items: center; gap: .6rem; margin-bottom: .35rem; }
    .bar-day { width: 90px; font-size: .8rem; color: #888; }
    .bar-track { flex: 1; background: #eee; border-radius: 6px; height: 18px; overflow: hidden; }
    .bar-fill { height: 100%; background: linear-gradient(90deg, #4a90d9, #2d5f9a); border-radius: 6px; }
    .bar-val { width: 70px; text-align: right; font-size: .8rem; }
    table { width: 100%; border-collapse: collapse; }
    td, th { text-align: left; padding: .35rem .5rem; border-bottom: 1px solid #eee; }
    @media (prefers-color-scheme: dark) {
      .card { border-color: #333; }
      .bar-track { background: #222; }
      td, th { border-bottom-color: #222; }
    }
  </style></head><body>
`)

	fmt.Fprintf(&b, "<h1>🛡 FocusGuard — Estatísticas de foco</h1>\n")
	fmt.Fprintf(&b, "<div class=\"sub\">Gerado em %s</div>\n", time.Now().Format("02/01/2006 15:04"))

	b.WriteString("<div class=\"cards\">\n")
	fmt.Fprintf(&b, "<div class=\"card\"><div class=\"k\">Sessões</div><div class=\"v\">%d</div></div>\n", st.TotalSessions)
	fmt.Fprintf(&b, "<div class=\"card\"><div class=\"k\">Tempo total</div><div class=\"v\">%s</div></div>\n", st.TotalFocus.Round(time.Minute))
	fmt.Fprintf(&b, "<div class=\"card\"><div class=\"k\">Raia de foco</div><div class=\"v\">%d dia(s)</div></div>\n", st.Streak)
	b.WriteString("</div>\n")

	// Barras por dia (largura proporcional ao dia com mais foco).
	b.WriteString("<h2>Foco por dia</h2>\n")
	max := time.Duration(0)
	for _, d := range st.PerDay {
		if d.Duration > max {
			max = d.Duration
		}
	}
	for _, d := range st.PerDay {
		pct := 0.0
		if max > 0 && d.Duration > 0 {
			pct = float64(d.Duration) / float64(max) * 100
		}
		b.WriteString("<div class=\"bar-row\">")
		fmt.Fprintf(&b, "<div class=\"bar-day\">%s</div>", d.Day)
		fmt.Fprintf(&b, "<div class=\"bar-track\"><div class=\"bar-fill\" style=\"width:%.1f%%\"></div></div>", pct)
		if d.Duration > 0 {
			fmt.Fprintf(&b, "<div class=\"bar-val\">%s</div>", d.Duration.Round(time.Minute))
		} else {
			b.WriteString("<div class=\"bar-val\">—</div>")
		}
		b.WriteString("</div>\n")
	}

	// Ranking de domínios.
	if len(st.PerDomain) > 0 {
		b.WriteString("<h2>Domínios mais bloqueados</h2>\n<table><thead><tr><th>Domínio</th><th>Foco</th></tr></thead><tbody>\n")
		for _, d := range st.PerDomain {
			fmt.Fprintf(&b, "<tr><td>%s</td><td>%s</td></tr>\n", html.EscapeString(d.Domain), d.Duration.Round(time.Minute))
		}
		b.WriteString("</tbody></table>\n")
	}

	b.WriteString("</body></html>\n")
	return b.String()
}

// RenderWeeklySummary renders a compact plain-text weekly digest from the
// Stats report: totals, per-active-day average, active days, streak and the
// top blocked domains.
func RenderWeeklySummary(st *Stats) string {
	var b strings.Builder
	b.WriteString("📊 Resumo semanal de foco\n")
	b.WriteString("───────────────────────\n")
	if st.TotalSessions == 0 {
		b.WriteString("Nenhuma sessão registrada na última semana — faça uma sessão de foco primeiro.\n")
		return b.String()
	}

	activeDays := 0
	for _, d := range st.PerDay {
		if d.Duration > 0 {
			activeDays++
		}
	}
	avg := time.Duration(0)
	if activeDays > 0 {
		avg = st.TotalFocus / time.Duration(activeDays)
	}

	fmt.Fprintf(&b, "Total de foco: %s (%d sessões)\n", st.TotalFocus.Round(time.Minute), st.TotalSessions)
	fmt.Fprintf(&b, "Dias com foco: %d de %d\n", activeDays, len(st.PerDay))
	if activeDays > 0 {
		fmt.Fprintf(&b, "Média por dia ativo: %s\n", avg.Round(time.Minute))
	}
	if st.Streak > 0 {
		fmt.Fprintf(&b, "🔥 Raia de foco: %d dia(s) consecutivo(s)\n", st.Streak)
	}
	if len(st.PerDomain) > 0 {
		b.WriteString("\nTop domínios bloqueados:\n")
		n := len(st.PerDomain)
		if n > 5 {
			n = 5
		}
		for _, d := range st.PerDomain[:n] {
			fmt.Fprintf(&b, "  %s  %s\n", d.Domain, d.Duration.Round(time.Minute))
		}
	}
	return b.String()
}

// RenderStats renders the report as an ASCII bar chart. The day with the most
// focus fills exactly barWidth block characters; days with no focus render no
// bar. Durations are rounded to the minute.
func RenderStats(st *Stats, barWidth int) string {
	var b strings.Builder

	fmt.Fprintf(&b, "FocusGuard — Estatísticas de foco\n\n")
	fmt.Fprintf(&b, "Sessões registradas: %d\n", st.TotalSessions)
	fmt.Fprintf(&b, "Tempo total de foco: %s\n", st.TotalFocus.Round(time.Minute))
	if st.Streak > 0 {
		fmt.Fprintf(&b, "🔥 Raia de foco: %d dia(s) consecutivo(s)\n", st.Streak)
	}
	fmt.Fprintln(&b)

	fmt.Fprintf(&b, "Foco por dia (últimos %d dias):\n", len(st.PerDay))
	max := time.Duration(0)
	for _, d := range st.PerDay {
		if d.Duration > max {
			max = d.Duration
		}
	}
	for _, d := range st.PerDay {
		barLen := 0
		if max > 0 && d.Duration > 0 {
			barLen = int(float64(d.Duration)/float64(max)*float64(barWidth) + 0.5)
			if barLen < 1 {
				barLen = 1
			}
		}
		fmt.Fprintf(&b, "%s  %s  %s\n", d.Day, strings.Repeat("█", barLen), d.Duration.Round(time.Minute))
	}

	if len(st.PerDomain) > 0 {
		fmt.Fprintf(&b, "\nDomínios mais bloqueados:\n")
		for _, d := range st.PerDomain {
			fmt.Fprintf(&b, "%s  %s\n", d.Domain, d.Duration.Round(time.Minute))
		}
	}

	return b.String()
}
